---
- name: Deploy Maven Artifact
  hosts: local
  become: yes
  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /opt/deployment
        state: directory
        mode: '0755'

    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/HelloMaven-CI/target/maven-example-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven.jar"
